### ISSUE TITLE
Find open issues

### ISSUE THREAD

**Issue by fpunny** [CSCD01/team_24-project#1]
**Description**
Find and analyze issues that can be worked on

**Progress**
 - [x] Find issues
 - [x] Pick issues to implement
 - [x] Discuss allocation of members to issues

**Comment by fpunny** [comment]
https://github.com/pandas-dev/pandas/issues/23988
**Type:** Bug
**Description**
Some guy seems to have this mostly done, but its been dead for a while. Maybe we can scope this one up

**Comment by fpunny** [comment]
**Issue Number:** 26278
**Type:** Feature
**Description**
Users want to automatically format columns in LATEX with a single command instead of multiple lambda functions.

**Comment by fpunny** [comment]
**Issue Number:** 28572
**Type:** Bug
**Description**
This is an issue brought up by a user to change the behaviour of the groupBy method for the Dataframe object and an inconsistency when group by is called and when groupby and sum is called in conjunction.

**Comment by SpectrumWings** [comment]
**Issue Number:** 9314
**Type** : Feature Enhancement
**Description**
User wants constants from DateUtil library for frequency such as MONTHLY, YEARLY etc. to be compatible as parameters for the date_range function for dataFrames. This requires bring this constants to this module itself.

**Comment by SpectrumWings** [comment]
**Type**: Bug
**Description:**
In the SparseDataFrame object, when trying to get the column name, a KeyError is thrown. Implementation of SparseDataFrame needs to be looked at, and may even be depreciated in the future.
https://github.com/pandas-dev/pandas/issues/18414

**Comment by SpectrumWings** [comment]
**Issue Number:** 18414
**Type**: Bug
**Description**
In the SparseDataFrame object, when trying to get the column name, a KeyError is thrown. Implementation of SparseDataFrame needs to be looked at, and may even be depreciated in the future.

**Comment by fpunny** [comment]
**Issue Number:** 23988
**Type:** Bug
**Description**
Some guy seems to have this mostly done, but its been dead for a while. Maybe we can scope this one up

**Comment by fpunny** [comment]
**Taskes to work on:** 13054 & 9314
**Team Allocation:**
 - **9314:** @fpunny, @SpectrumWings, @mason-98
 - **26278:** @wlgranados, @jadenyjw
