### ISSUE TITLE
[Issue 9314] - date_range enhancement to accept DateUtil freq constants

### ISSUE THREAD

**Issue by fpunny** [CSCD01/team_24-project#3]
**Description of Issue**
User wants constants from DateUtil library for frequency such as MONTHLY, YEARLY etc. to be compatible as parameters for the date_range function for dataFrames. This requires bring this constants to this module itself.

**Progress**
 - [x] Define Estimate
 - [x] Propose Solution (and await feedback from team)
 - [x] Development
 - [x] Testing
 - [x] Final Review

**Comment by mason-98** [comment]
Proposed Solution: Identified the values of the constants (MONTHLY, YEARLY etc) from DateUtil  are integers. So we will change the function date_range to accept the corresponding integer values and process it according to the constant name

**Comment by SpectrumWings** [comment]
Task has been completed and reviewed
